source "https://rubygems.org"

# GitHub Pages compatible gems
gem "github-pages", group: :jekyll_plugins
gem "jekyll-github-metadata", group: :jekyll_plugins

# AsciiDoc processors
gem "asciidoctor", "~> 2.0"
gem "asciidoctor-pdf", "~> 2.3"
gem "asciidoctor-diagram", "~> 2.2"
gem "asciidoctor-rouge", "~> 0.5"

# Syntax highlighting
gem "rouge", "~> 4.0"

# Development tools
gem "bundler", "~> 2.0"
